### PR TITLE
Fix tern start (KO with recent lighttable version)

### PR DESCRIPTION
**Pull request by Armaklan**
This plugin dont work with recent lighttable version => it use a thread function which was deleted.

This PR fix with new version.

### CODE REVIEW

**Comment by mortalapeman** [comment]
Will check this out tonight in a few hours. Thanks for the PR sand taking the time to fix it.

**Comment by Armaklan** [comment]
I still have other bug.

- Server isn't start
- Call ternjs feature
- Server start
- Features work
- Wait 30 sec
- Call ternjs feature
- No effet, no error

I try to find the bug next night...

**Comment by mortalapeman** [comment]
I ended up with no free time last night for this merge (sigh). I'll try to test the plugin sometime this week if you don't get to it first.

If the features work for a few seconds and then stops, I fear it has something to do with the tern server getting caught in a loop, and might require an update to the newest tern server. Unfortunately, the new server resolves relative file paths in a way that isn't conducive with the way I had originally designed this plugin (at least that was true last time I checked). It's going to be a big hurdle to try and make the new server compatible with the plugin and the way light table handles workspaces, but I'm pretty sure it's doable.

**Comment by Armaklan** [comment]
New fix. Seens to be correct (Work on windows without stops)

**Comment by Armaklan** [comment]
This last version work. It's ready to merge.

I have problem with an ECMA6 projet (with class and other features), but i think is another issue.

**Comment by Armaklan** [comment]
Can you merge this PR ?

**New ternjs version**

About new version of ternJs, can you tell me more ? I try with last version and : 

- Inside a file, doc work
- Jump to seen not work

Maybe can i try to make the migration :) .

**Comment by mortalapeman** [comment]
Sorry, I'm just at a weird place in life, and finding the time + motivation to work on this even small task is difficult for me. I have added you as a collaborator so you have push access. If you'd like to fork and maintain this project on your own, you have my blessing to do so. I am really glad you have found this codebase useful and I regret not being able to properly maintain it over the past several months.

**Comment by Armaklan** [comment]
Ok ! 
Thx to add me on project. I will push and release it, and try to migrate to new Tern :)

**Pull request merged**
